using Domain.Entities;
using Infrastructure.Database.DatabaseContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Database.DatabaseSeeds.SeedEntities
{
    public static class SeedCountries
    {        
        public static async Task SeedCountriesDataAsync(ApplicationDbContext context)
        {
            
            if (context.Countries.Any())
            {
                return;   // DB has been seeded
            }
            context.Countries.AddRange(                
                new Country { FifaAlphaCode = "AFG", CountryName = "Afghanistan" },
                new Country { FifaAlphaCode = "ALB", CountryName = "Albania" },
                new Country { FifaAlphaCode = "ALG", CountryName = "Algeria" },
                new Country { FifaAlphaCode = "ASA", CountryName = "American Samoa" },
                new Country { FifaAlphaCode = "AND", CountryName = "Andorra" },
                new Country { FifaAlphaCode = "ANG", CountryName = "Angola" },
                new Country { FifaAlphaCode = "AIA", CountryName = "Anguilla" },
                new Country { FifaAlphaCode = "ATG", CountryName = "Antigua and Barbuda" },
                new Country { FifaAlphaCode = "ARG", CountryName = "Argentina" },
                new Country { FifaAlphaCode = "ARM", CountryName = "Armenia" },
                new Country { FifaAlphaCode = "ARU", CountryName = "Aruba" },
                new Country { FifaAlphaCode = "AUS", CountryName = "Australia" },
                new Country { FifaAlphaCode = "AUT", CountryName = "Austria" },
                new Country { FifaAlphaCode = "AZE", CountryName = "Azerbaijan" },
                new Country { FifaAlphaCode = "BAH", CountryName = "Bahamas" },
                new Country { FifaAlphaCode = "BHR", CountryName = "Bahrain" },
                new Country { FifaAlphaCode = "BAN", CountryName = "Bangladesh" },
                new Country { FifaAlphaCode = "BRB", CountryName = "Barbados" },
                new Country { FifaAlphaCode = "BLR", CountryName = "Belarus" },
                new Country { FifaAlphaCode = "BEL", CountryName = "Belgium" },
                new Country { FifaAlphaCode = "BLZ", CountryName = "Belize" },
                new Country { FifaAlphaCode = "BEN", CountryName = "Benin" },
                new Country { FifaAlphaCode = "BER", CountryName = "Bermuda" },
                new Country { FifaAlphaCode = "BHU", CountryName = "Bhutan" },
                new Country { FifaAlphaCode = "BOL", CountryName = "Bolivia" },
                new Country { FifaAlphaCode = "BIH", CountryName = "Bosnia and Herzegovina" },
                new Country { FifaAlphaCode = "BOT", CountryName = "Botswana" },
                new Country { FifaAlphaCode = "BRA", CountryName = "Brazil" },
                new Country { FifaAlphaCode = "VGB", CountryName = "British Virgin Islands" },
                new Country { FifaAlphaCode = "BRU", CountryName = "Brunei" },
                new Country { FifaAlphaCode = "BUL", CountryName = "Bulgaria" },
                new Country { FifaAlphaCode = "BFA", CountryName = "Burkina Faso" },
                new Country { FifaAlphaCode = "BDI", CountryName = "Burundi" },
                new Country { FifaAlphaCode = "CAM", CountryName = "Cambodia" },
                new Country { FifaAlphaCode = "CMR", CountryName = "Cameroon" },
                new Country { FifaAlphaCode = "CAN", CountryName = "Canada" },
                new Country { FifaAlphaCode = "CPV", CountryName = "Cape Verde" },
                new Country { FifaAlphaCode = "CAY", CountryName = "Cayman Islands" },
                new Country { FifaAlphaCode = "CTA", CountryName = "Central African Republic" },
                new Country { FifaAlphaCode = "CHA", CountryName = "Chad" },
                new Country { FifaAlphaCode = "CHI", CountryName = "Chile" },
                new Country { FifaAlphaCode = "CHN", CountryName = "China PR" },
                new Country { FifaAlphaCode = "TPE", CountryName = "Chinese Taipei" },
                new Country { FifaAlphaCode = "COL", CountryName = "Colombia" },
                new Country { FifaAlphaCode = "COM", CountryName = "Comoros" },
                new Country { FifaAlphaCode = "CGO", CountryName = "Congo" },
                new Country { FifaAlphaCode = "COK", CountryName = "Cook Islands" },
                new Country { FifaAlphaCode = "CRC", CountryName = "Costa Rica" },
                new Country { FifaAlphaCode = "CRO", CountryName = "Croatia" },
                new Country { FifaAlphaCode = "CUB", CountryName = "Cuba" },
                new Country { FifaAlphaCode = "CUW", CountryName = "Curaçao" },
                new Country { FifaAlphaCode = "CYP", CountryName = "Cyprus" },
                new Country { FifaAlphaCode = "CZE", CountryName = "Czech Republic" },
                new Country { FifaAlphaCode = "DEN", CountryName = "Denmark" },
                new Country { FifaAlphaCode = "DJI", CountryName = "Djibouti" },
                new Country { FifaAlphaCode = "DMA", CountryName = "Dominica" },
                new Country { FifaAlphaCode = "DOM", CountryName = "Dominican Republic" },
                new Country { FifaAlphaCode = "COD", CountryName = "DR Congo" },
                new Country { FifaAlphaCode = "ECU", CountryName = "Ecuador" },
                new Country { FifaAlphaCode = "EGY", CountryName = "Egypt" },
                new Country { FifaAlphaCode = "SLV", CountryName = "El Salvador" },
                new Country { FifaAlphaCode = "ENG", CountryName = "England" },
                new Country { FifaAlphaCode = "EQG", CountryName = "Equatorial Guinea" },
                new Country { FifaAlphaCode = "ERI", CountryName = "Eritrea" },
                new Country { FifaAlphaCode = "EST", CountryName = "Estonia" },
                new Country { FifaAlphaCode = "SWZ", CountryName = "Eswatini" },
                new Country { FifaAlphaCode = "ETH", CountryName = "Ethiopia" },
                new Country { FifaAlphaCode = "FRO", CountryName = "Faroe Islands" },
                new Country { FifaAlphaCode = "FIJ", CountryName = "Fiji" },
                new Country { FifaAlphaCode = "FIN", CountryName = "Finland" },
                new Country { FifaAlphaCode = "FRA", CountryName = "France" },
                new Country { FifaAlphaCode = "GAB", CountryName = "Gabon" },
                new Country { FifaAlphaCode = "GAM", CountryName = "Gambia" },
                new Country { FifaAlphaCode = "GEO", CountryName = "Georgia" },
                new Country { FifaAlphaCode = "GER", CountryName = "Germany" },
                new Country { FifaAlphaCode = "GHA", CountryName = "Ghana" },
                new Country { FifaAlphaCode = "GIB", CountryName = "Gibraltar" },
                new Country { FifaAlphaCode = "GRE", CountryName = "Greece" },
                new Country { FifaAlphaCode = "GRN", CountryName = "Grenada" },
                new Country { FifaAlphaCode = "GUM", CountryName = "Guam" },
                new Country { FifaAlphaCode = "GUA", CountryName = "Guatemala" },
                new Country { FifaAlphaCode = "GUI", CountryName = "Guinea" },
                new Country { FifaAlphaCode = "GNB", CountryName = "Guinea-Bissau" },
                new Country { FifaAlphaCode = "GUY", CountryName = "Guyana" },
                new Country { FifaAlphaCode = "HAI", CountryName = "Haiti" },
                new Country { FifaAlphaCode = "HON", CountryName = "Honduras" },
                new Country { FifaAlphaCode = "HKG", CountryName = "Hong Kong" },
                new Country { FifaAlphaCode = "HUN", CountryName = "Hungary" },
                new Country { FifaAlphaCode = "ISL", CountryName = "Iceland" },
                new Country { FifaAlphaCode = "IND", CountryName = "India" },
                new Country { FifaAlphaCode = "IDN", CountryName = "Indonesia" },
                new Country { FifaAlphaCode = "IRN", CountryName = "Iran" },
                new Country { FifaAlphaCode = "IRQ", CountryName = "Iraq" },
                new Country { FifaAlphaCode = "ISR", CountryName = "Israel" },
                new Country { FifaAlphaCode = "ITA", CountryName = "Italy" },
                new Country { FifaAlphaCode = "CIV", CountryName = "Ivory Coast" },
                new Country { FifaAlphaCode = "JAM", CountryName = "Jamaica" },
                new Country { FifaAlphaCode = "JPN", CountryName = "Japan" },
                new Country { FifaAlphaCode = "JOR", CountryName = "Jordan" },
                new Country { FifaAlphaCode = "KAZ", CountryName = "Kazakhstan" },
                new Country { FifaAlphaCode = "KEN", CountryName = "Kenya" },
                new Country { FifaAlphaCode = "KVX", CountryName = "Kosovo" },
                new Country { FifaAlphaCode = "KUW", CountryName = "Kuwait" },
                new Country { FifaAlphaCode = "KGZ", CountryName = "Kyrgyzstan" },
                new Country { FifaAlphaCode = "LAO", CountryName = "Laos" },
                new Country { FifaAlphaCode = "LVA", CountryName = "Latvia" },
                new Country { FifaAlphaCode = "LBN", CountryName = "Lebanon" },
                new Country { FifaAlphaCode = "LES", CountryName = "Lesotho" },
                new Country { FifaAlphaCode = "LBR", CountryName = "Liberia" },
                new Country { FifaAlphaCode = "LBY", CountryName = "Libya" },
                new Country { FifaAlphaCode = "LIE", CountryName = "Liechtenstein" },
                new Country { FifaAlphaCode = "LTU", CountryName = "Lithuania" },
                new Country { FifaAlphaCode = "LUX", CountryName = "Luxembourg" },
                new Country { FifaAlphaCode = "MAC", CountryName = "Macau" },
                new Country { FifaAlphaCode = "MAD", CountryName = "Madagascar" },
                new Country { FifaAlphaCode = "MWI", CountryName = "Malawi" },
                new Country { FifaAlphaCode = "MAS", CountryName = "Malaysia" },
                new Country { FifaAlphaCode = "MDV", CountryName = "Maldives" },
                new Country { FifaAlphaCode = "MLI", CountryName = "Mali" },
                new Country { FifaAlphaCode = "MLT", CountryName = "Malta" },
                new Country { FifaAlphaCode = "MTN", CountryName = "Mauritania" },
                new Country { FifaAlphaCode = "MRI", CountryName = "Mauritius" },
                new Country { FifaAlphaCode = "MEX", CountryName = "Mexico" },
                new Country { FifaAlphaCode = "MDA", CountryName = "Moldova" },
                new Country { FifaAlphaCode = "MNG", CountryName = "Mongolia" },
                new Country { FifaAlphaCode = "MNE", CountryName = "Montenegro" },
                new Country { FifaAlphaCode = "MSR", CountryName = "Montserrat" },
                new Country { FifaAlphaCode = "MAR", CountryName = "Morocco" },
                new Country { FifaAlphaCode = "MOZ", CountryName = "Mozambique" },
                new Country { FifaAlphaCode = "MYA", CountryName = "Myanmar" },
                new Country { FifaAlphaCode = "NAM", CountryName = "Namibia" },
                new Country { FifaAlphaCode = "NEP", CountryName = "Nepal" },
                new Country { FifaAlphaCode = "NED", CountryName = "Netherlands" },
                new Country { FifaAlphaCode = "NCL", CountryName = "New Caledonia" },
                new Country { FifaAlphaCode = "NZL", CountryName = "New Zealand" },
                new Country { FifaAlphaCode = "NCA", CountryName = "Nicaragua" },
                new Country { FifaAlphaCode = "NIG", CountryName = "Niger" },
                new Country { FifaAlphaCode = "NGA", CountryName = "Nigeria" },
                new Country { FifaAlphaCode = "PRK", CountryName = "North Korea" },
                new Country { FifaAlphaCode = "MKD", CountryName = "North Macedonia" },
                new Country { FifaAlphaCode = "NIR", CountryName = "Northern Ireland" },
                new Country { FifaAlphaCode = "NOR", CountryName = "Norway" },
                new Country { FifaAlphaCode = "OMA", CountryName = "Oman" },
                new Country { FifaAlphaCode = "PAK", CountryName = "Pakistan" },
                new Country { FifaAlphaCode = "PLE", CountryName = "Palestine" },
                new Country { FifaAlphaCode = "PAN", CountryName = "Panama" },
                new Country { FifaAlphaCode = "PNG", CountryName = "Papua New Guinea" },
                new Country { FifaAlphaCode = "PAR", CountryName = "Paraguay" },
                new Country { FifaAlphaCode = "PER", CountryName = "Peru" },
                new Country { FifaAlphaCode = "PHI", CountryName = "Philippines" },
                new Country { FifaAlphaCode = "POL", CountryName = "Poland" },
                new Country { FifaAlphaCode = "POR", CountryName = "Portugal" },
                new Country { FifaAlphaCode = "PUR", CountryName = "Puerto Rico" },
                new Country { FifaAlphaCode = "QAT", CountryName = "Qatar" },
                new Country { FifaAlphaCode = "IRL", CountryName = "Republic of Ireland" },
                new Country { FifaAlphaCode = "ROU", CountryName = "Romania" },
                new Country { FifaAlphaCode = "RUS", CountryName = "Russia" },
                new Country { FifaAlphaCode = "RWA", CountryName = "Rwanda" },
                new Country { FifaAlphaCode = "SKN", CountryName = "Saint Kitts and Nevis" },
                new Country { FifaAlphaCode = "LCA", CountryName = "Saint Lucia" },
                new Country { FifaAlphaCode = "VIN", CountryName = "Saint Vincent and the Grenadines" },
                new Country { FifaAlphaCode = "SAM", CountryName = "Samoa" },
                new Country { FifaAlphaCode = "SMR", CountryName = "San Marino" },
                new Country { FifaAlphaCode = "STP", CountryName = "São Tomé and Príncipe" },
                new Country { FifaAlphaCode = "KSA", CountryName = "Saudi Arabia" },
                new Country { FifaAlphaCode = "SCO", CountryName = "Scotland" },
                new Country { FifaAlphaCode = "SEN", CountryName = "Senegal" },
                new Country { FifaAlphaCode = "SRB", CountryName = "Serbia" },
                new Country { FifaAlphaCode = "SEY", CountryName = "Seychelles" },
                new Country { FifaAlphaCode = "SLE", CountryName = "Sierra Leone" },
                new Country { FifaAlphaCode = "SIN", CountryName = "Singapore" },
                new Country { FifaAlphaCode = "SVK", CountryName = "Slovakia" },
                new Country { FifaAlphaCode = "SVN", CountryName = "Slovenia" },
                new Country { FifaAlphaCode = "SOL", CountryName = "Solomon Islands" },
                new Country { FifaAlphaCode = "SOM", CountryName = "Somalia" },
                new Country { FifaAlphaCode = "RSA", CountryName = "South Africa" },
                new Country { FifaAlphaCode = "KOR", CountryName = "South Korea" },
                new Country { FifaAlphaCode = "SSD", CountryName = "South Sudan" },
                new Country { FifaAlphaCode = "ESP", CountryName = "Spain" },
                new Country { FifaAlphaCode = "SRI", CountryName = "Sri Lanka" },
                new Country { FifaAlphaCode = "SDN", CountryName = "Sudan" },
                new Country { FifaAlphaCode = "SUR", CountryName = "Suriname" },
                new Country { FifaAlphaCode = "SWE", CountryName = "Sweden" },
                new Country { FifaAlphaCode = "SUI", CountryName = "Switzerland" },
                new Country { FifaAlphaCode = "SYR", CountryName = "Syria" },
                new Country { FifaAlphaCode = "TAH", CountryName = "Tahiti" },
                new Country { FifaAlphaCode = "TJK", CountryName = "Tajikistan" },
                new Country { FifaAlphaCode = "TAN", CountryName = "Tanzania" },
                new Country { FifaAlphaCode = "THA", CountryName = "Thailand" },
                new Country { FifaAlphaCode = "TLS", CountryName = "Timor-Leste" },
                new Country { FifaAlphaCode = "TOG", CountryName = "Togo" },
                new Country { FifaAlphaCode = "TGA", CountryName = "Tonga" },
                new Country { FifaAlphaCode = "TRI", CountryName = "Trinidad and Tobago" },
                new Country { FifaAlphaCode = "TUN", CountryName = "Tunisia" },
                new Country { FifaAlphaCode = "TUR", CountryName = "Turkey" },
                new Country { FifaAlphaCode = "TKM", CountryName = "Turkmenistan" },
                new Country { FifaAlphaCode = "TCA", CountryName = "Turks and Caicos Islands" },
                new Country { FifaAlphaCode = "UGA", CountryName = "Uganda" },
                new Country { FifaAlphaCode = "UKR", CountryName = "Ukraine" },
                new Country { FifaAlphaCode = "UAE", CountryName = "United Arab Emirates" },
                new Country { FifaAlphaCode = "USA", CountryName = "United States" },
                new Country { FifaAlphaCode = "URU", CountryName = "Uruguay" },
                new Country { FifaAlphaCode = "VIR", CountryName = "U.S. Virgin Islands" },
                new Country { FifaAlphaCode = "UZB", CountryName = "Uzbekistan" },
                new Country { FifaAlphaCode = "VAN", CountryName = "Vanuatu" },
                new Country { FifaAlphaCode = "VEN", CountryName = "Venezuela" },
                new Country { FifaAlphaCode = "VIE", CountryName = "Vietnam" },
                new Country { FifaAlphaCode = "WAL", CountryName = "Wales" },
                new Country { FifaAlphaCode = "YEM", CountryName = "Yemen" },
                new Country { FifaAlphaCode = "ZAM", CountryName = "Zambia" },
                new Country { FifaAlphaCode = "ZIM", CountryName = "Zimbabwe" },
                new Country { FifaAlphaCode = "TCH", CountryName = "Czechoslovakia" },
                new Country { FifaAlphaCode = "GDR", CountryName = "East Germany" },
                new Country { FifaAlphaCode = "SCG", CountryName = "Serbia and Montenegro" },
                new Country { FifaAlphaCode = "URS", CountryName = "Soviet Union" },
                new Country { FifaAlphaCode = "ZAI", CountryName = "Zaire" },
                new Country { FifaAlphaCode = "YUG", CountryName = "Yugoslavia" },
                new Country { FifaAlphaCode = "INH", CountryName = "Dutch East Indies" },
                new Country { FifaAlphaCode = "FRG", CountryName = "West Germany" }
             );
            context.SaveChanges();
            await context.SaveChangesAsync();
        }
    }
}
