using Domain.Entities;
using Infrastructure.Database.DatabaseContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Database.DatabaseSeeds.SeedEntities
{
    public static class SeedTeams
    {
        public static async Task SeedTeamsDataAsync(ApplicationDbContext context)
        {

            if (context.Teams.Any())
            {
                return;   // DB has been seeded
            }
            context.Teams.AddRange(                
                new Team { TeamName = "Afghanistan", FifaAlphaCode = "AFG", TeamCode = "AFG", TypeName="National" },
                new Team { TeamName = "Albania", FifaAlphaCode = "ALB", TeamCode = "ALB", TypeName= "National" },
                new Team { TeamName = "Algeria", FifaAlphaCode = "ALG", TeamCode = "ALG", TypeName= "National" },
                new Team { TeamName = "American Samoa", FifaAlphaCode = "ASA", TeamCode = "ASA", TypeName= "National" },
                new Team { TeamName = "Andorra", FifaAlphaCode = "AND", TeamCode = "AND", TypeName= "National" },
                new Team { TeamName = "Angola", FifaAlphaCode = "ANG", TeamCode = "ANG", TypeName= "National" },
                new Team { TeamName = "Anguilla", FifaAlphaCode = "AIA", TeamCode = "AIA", TypeName= "National" },
                new Team { TeamName = "Antigua and Barbuda", FifaAlphaCode = "ATG", TeamCode = "ATG", TypeName= "National" },
                new Team { TeamName = "Argentina", FifaAlphaCode = "ARG", TeamCode = "ARG", TypeName= "National" },
                new Team { TeamName = "Armenia", FifaAlphaCode = "ARM", TeamCode = "ARM", TypeName= "National" },
                new Team { TeamName = "Aruba", FifaAlphaCode = "ARU", TeamCode = "ARU", TypeName= "National" },
                new Team { TeamName = "Australia", FifaAlphaCode = "AUS", TeamCode = "AUS", TypeName= "National" },
                new Team { TeamName = "Austria", FifaAlphaCode = "AUT", TeamCode = "AUT", TypeName= "National" },
                new Team { TeamName = "Azerbaijan", FifaAlphaCode = "AZE", TeamCode = "AZE", TypeName= "National" },
                new Team { TeamName = "Bahamas", FifaAlphaCode = "BAH", TeamCode = "BAH", TypeName= "National" },
                new Team { TeamName = "Bahrain", FifaAlphaCode = "BHR", TeamCode = "BHR", TypeName= "National" },
                new Team { TeamName = "Bangladesh", FifaAlphaCode = "BAN", TeamCode = "BAN", TypeName= "National" },
                new Team { TeamName = "Barbados", FifaAlphaCode = "BRB", TeamCode = "BRB", TypeName= "National" },
                new Team { TeamName = "Belarus", FifaAlphaCode = "BLR", TeamCode = "BLR", TypeName= "National" },
                new Team { TeamName = "Belgium", FifaAlphaCode = "BEL", TeamCode = "BEL", TypeName= "National" },
                new Team { TeamName = "Belize", FifaAlphaCode = "BLZ", TeamCode = "BLZ", TypeName= "National" },
                new Team { TeamName = "Benin", FifaAlphaCode = "BEN", TeamCode = "BEN", TypeName= "National" },
                new Team { TeamName = "Bermuda", FifaAlphaCode = "BER", TeamCode = "BER", TypeName= "National" },
                new Team { TeamName = "Bhutan", FifaAlphaCode = "BHU", TeamCode = "BHU", TypeName= "National" },
                new Team { TeamName = "Bolivia", FifaAlphaCode = "BOL", TeamCode = "BOL", TypeName= "National" },
                new Team { TeamName = "Bosnia and Herzegovina", FifaAlphaCode = "BIH", TeamCode = "BIH", TypeName= "National" },
                new Team { TeamName = "Botswana", FifaAlphaCode = "BOT", TeamCode = "BOT", TypeName= "National" },
                new Team { TeamName = "Brazil", FifaAlphaCode = "BRA", TeamCode = "BRA", TypeName= "National" },
                new Team { TeamName = "British Virgin Islands", FifaAlphaCode = "VGB", TeamCode = "VGB", TypeName= "National" },
                new Team { TeamName = "Brunei", FifaAlphaCode = "BRU", TeamCode = "BRU", TypeName= "National" },
                new Team { TeamName = "Bulgaria", FifaAlphaCode = "BUL", TeamCode = "BUL", TypeName= "National" },
                new Team { TeamName = "Burkina Faso", FifaAlphaCode = "BFA", TeamCode = "BFA", TypeName= "National" },
                new Team { TeamName = "Burundi", FifaAlphaCode = "BDI", TeamCode = "BDI", TypeName= "National" },
                new Team { TeamName = "Cambodia", FifaAlphaCode = "CAM", TeamCode = "CAM", TypeName= "National" },
                new Team { TeamName = "Cameroon", FifaAlphaCode = "CMR", TeamCode = "CMR", TypeName= "National" },
                new Team { TeamName = "Canada", FifaAlphaCode = "CAN", TeamCode = "CAN", TypeName= "National" },
                new Team { TeamName = "Cape Verde", FifaAlphaCode = "CPV", TeamCode = "CPV", TypeName= "National" },
                new Team { TeamName = "Cayman Islands", FifaAlphaCode = "CAY", TeamCode = "CAY", TypeName= "National" },
                new Team { TeamName = "Central African Republic", FifaAlphaCode = "CTA", TeamCode = "CTA", TypeName= "National" },
                new Team { TeamName = "Chad", FifaAlphaCode = "CHA", TeamCode = "CHA", TypeName= "National" },
                new Team { TeamName = "Chile", FifaAlphaCode = "CHI", TeamCode = "CHI", TypeName= "National" },
                new Team { TeamName = "China", FifaAlphaCode = "CHN", TeamCode = "CHN", TypeName= "National" },
                new Team { TeamName = "Chinese Taipei", FifaAlphaCode = "TPE", TeamCode = "TPE", TypeName= "National" },
                new Team { TeamName = "Colombia", FifaAlphaCode = "COL", TeamCode = "COL", TypeName= "National" },
                new Team { TeamName = "Comoros", FifaAlphaCode = "COM", TeamCode = "COM", TypeName= "National" },
                new Team { TeamName = "Congo", FifaAlphaCode = "CGO", TeamCode = "CGO", TypeName= "National" },
                new Team { TeamName = "Cook Islands", FifaAlphaCode = "COK", TeamCode = "COK", TypeName= "National" },
                new Team { TeamName = "Costa Rica", FifaAlphaCode = "CRC", TeamCode = "CRC", TypeName= "National" },
                new Team { TeamName = "Croatia", FifaAlphaCode = "CRO", TeamCode = "CRO", TypeName= "National" },
                new Team { TeamName = "Cuba", FifaAlphaCode = "CUB", TeamCode = "CUB", TypeName= "National" },
                new Team { TeamName = "Curaçao", FifaAlphaCode = "CUW", TeamCode = "CUW", TypeName= "National" },
                new Team { TeamName = "Cyprus", FifaAlphaCode = "CYP", TeamCode = "CYP", TypeName= "National" },
                new Team { TeamName = "Czech Republic", FifaAlphaCode = "CZE", TeamCode = "CZE", TypeName= "National" },
                new Team { TeamName = "Denmark", FifaAlphaCode = "DEN", TeamCode = "DEN", TypeName= "National" },
                new Team { TeamName = "Djibouti", FifaAlphaCode = "DJI", TeamCode = "DJI", TypeName= "National" },
                new Team { TeamName = "Dominica", FifaAlphaCode = "DMA", TeamCode = "DMA", TypeName= "National" },
                new Team { TeamName = "Dominican Republic", FifaAlphaCode = "DOM", TeamCode = "DOM", TypeName= "National" },
                new Team { TeamName = "DR Congo", FifaAlphaCode = "COD", TeamCode = "COD", TypeName= "National" },
                new Team { TeamName = "Ecuador", FifaAlphaCode = "ECU", TeamCode = "ECU", TypeName= "National" },
                new Team { TeamName = "Egypt", FifaAlphaCode = "EGY", TeamCode = "EGY", TypeName= "National" },
                new Team { TeamName = "El Salvador", FifaAlphaCode = "SLV", TeamCode = "SLV", TypeName= "National" },
                new Team { TeamName = "England", FifaAlphaCode = "ENG", TeamCode = "ENG", TypeName= "National" },
                new Team { TeamName = "Equatorial Guinea", FifaAlphaCode = "EQG", TeamCode = "EQG", TypeName= "National" },
                new Team { TeamName = "Eritrea", FifaAlphaCode = "ERI", TeamCode = "ERI", TypeName= "National" },
                new Team { TeamName = "Estonia", FifaAlphaCode = "EST", TeamCode = "EST", TypeName= "National" },
                new Team { TeamName = "Eswatini", FifaAlphaCode = "SWZ", TeamCode = "SWZ", TypeName= "National" },
                new Team { TeamName = "Ethiopia", FifaAlphaCode = "ETH", TeamCode = "ETH", TypeName= "National" },
                new Team { TeamName = "Faroe Islands", FifaAlphaCode = "FRO", TeamCode = "FRO", TypeName= "National" },
                new Team { TeamName = "Fiji", FifaAlphaCode = "FIJ", TeamCode = "FIJ", TypeName= "National" },
                new Team { TeamName = "Finland", FifaAlphaCode = "FIN", TeamCode = "FIN", TypeName= "National" },
                new Team { TeamName = "France", FifaAlphaCode = "FRA", TeamCode = "FRA", TypeName= "National" },
                new Team { TeamName = "Gabon", FifaAlphaCode = "GAB", TeamCode = "GAB", TypeName= "National" },
                new Team { TeamName = "Gambia", FifaAlphaCode = "GAM", TeamCode = "GAM", TypeName= "National" },
                new Team { TeamName = "Georgia", FifaAlphaCode = "GEO", TeamCode = "GEO", TypeName= "National" },
                new Team { TeamName = "Germany", FifaAlphaCode = "GER", TeamCode = "GER", TypeName= "National" },
                new Team { TeamName = "Ghana", FifaAlphaCode = "GHA", TeamCode = "GHA", TypeName= "National" },
                new Team { TeamName = "Gibraltar", FifaAlphaCode = "GIB", TeamCode = "GIB", TypeName= "National" },
                new Team { TeamName = "Greece", FifaAlphaCode = "GRE", TeamCode = "GRE", TypeName= "National" },
                new Team { TeamName = "Grenada", FifaAlphaCode = "GRN", TeamCode = "GRN", TypeName= "National" },
                new Team { TeamName = "Guam", FifaAlphaCode = "GUM", TeamCode = "GUM", TypeName= "National" },
                new Team { TeamName = "Guatemala", FifaAlphaCode = "GUA", TeamCode = "GUA", TypeName= "National" },
                new Team { TeamName = "Guinea", FifaAlphaCode = "GUI", TeamCode = "GUI", TypeName= "National" },
                new Team { TeamName = "Guinea-Bissau", FifaAlphaCode = "GNB", TeamCode = "GNB", TypeName= "National" },
                new Team { TeamName = "Guyana", FifaAlphaCode = "GUY", TeamCode = "GUY", TypeName= "National" },
                new Team { TeamName = "Haiti", FifaAlphaCode = "HAI", TeamCode = "HAI", TypeName= "National" },
                new Team { TeamName = "Honduras", FifaAlphaCode = "HON", TeamCode = "HON", TypeName= "National" },
                new Team { TeamName = "Hong Kong", FifaAlphaCode = "HKG", TeamCode = "HKG", TypeName= "National" },
                new Team { TeamName = "Hungary", FifaAlphaCode = "HUN", TeamCode = "HUN", TypeName= "National" },
                new Team { TeamName = "Iceland", FifaAlphaCode = "ISL", TeamCode = "ISL", TypeName= "National" },
                new Team { TeamName = "India", FifaAlphaCode = "IND", TeamCode = "IND", TypeName= "National" },
                new Team { TeamName = "Indonesia", FifaAlphaCode = "IDN", TeamCode = "IDN", TypeName= "National" },
                new Team { TeamName = "Iran", FifaAlphaCode = "IRN", TeamCode = "IRN", TypeName= "National" },
                new Team { TeamName = "Iraq", FifaAlphaCode = "IRQ", TeamCode = "IRQ", TypeName= "National" },
                new Team { TeamName = "Israel", FifaAlphaCode = "ISR", TeamCode = "ISR", TypeName= "National" },
                new Team { TeamName = "Italy", FifaAlphaCode = "ITA", TeamCode = "ITA", TypeName= "National" },
                new Team { TeamName = "Ivory Coast", FifaAlphaCode = "CIV", TeamCode = "CIV", TypeName= "National" },
                new Team { TeamName = "Jamaica", FifaAlphaCode = "JAM", TeamCode = "JAM", TypeName= "National" },
                new Team { TeamName = "Japan", FifaAlphaCode = "JPN", TeamCode = "JPN", TypeName= "National" },
                new Team { TeamName = "Jordan", FifaAlphaCode = "JOR", TeamCode = "JOR", TypeName= "National" },
                new Team { TeamName = "Kazakhstan", FifaAlphaCode = "KAZ", TeamCode = "KAZ", TypeName= "National" },
                new Team { TeamName = "Kenya", FifaAlphaCode = "KEN", TeamCode = "KEN", TypeName= "National" },
                new Team { TeamName = "Kosovo", FifaAlphaCode = "KVX", TeamCode = "KVX", TypeName= "National" },
                new Team { TeamName = "Kuwait", FifaAlphaCode = "KUW", TeamCode = "KUW", TypeName= "National" },
                new Team { TeamName = "Kyrgyzstan", FifaAlphaCode = "KGZ", TeamCode = "KGZ", TypeName= "National" },
                new Team { TeamName = "Laos", FifaAlphaCode = "LAO", TeamCode = "LAO", TypeName= "National" },
                new Team { TeamName = "Latvia", FifaAlphaCode = "LVA", TeamCode = "LVA", TypeName= "National" },
                new Team { TeamName = "Lebanon", FifaAlphaCode = "LBN", TeamCode = "LBN", TypeName= "National" },
                new Team { TeamName = "Lesotho", FifaAlphaCode = "LES", TeamCode = "LES", TypeName= "National" },
                new Team { TeamName = "Liberia", FifaAlphaCode = "LBR", TeamCode = "LBR", TypeName= "National" },
                new Team { TeamName = "Libya", FifaAlphaCode = "LBY", TeamCode = "LBY", TypeName= "National" },
                new Team { TeamName = "Liechtenstein", FifaAlphaCode = "LIE", TeamCode = "LIE", TypeName= "National" },
                new Team { TeamName = "Lithuania", FifaAlphaCode = "LTU", TeamCode = "LTU", TypeName= "National" },
                new Team { TeamName = "Luxembourg", FifaAlphaCode = "LUX", TeamCode = "LUX", TypeName= "National" },
                new Team { TeamName = "Macau", FifaAlphaCode = "MAC", TeamCode = "MAC", TypeName= "National" },
                new Team { TeamName = "Madagascar", FifaAlphaCode = "MAD", TeamCode = "MAD", TypeName= "National" },
                new Team { TeamName = "Malawi", FifaAlphaCode = "MWI", TeamCode = "MWI", TypeName= "National" },
                new Team { TeamName = "Malaysia", FifaAlphaCode = "MAS", TeamCode = "MAS", TypeName= "National" },
                new Team { TeamName = "Maldives", FifaAlphaCode = "MDV", TeamCode = "MDV", TypeName= "National" },
                new Team { TeamName = "Mali", FifaAlphaCode = "MLI", TeamCode = "MLI", TypeName= "National" },
                new Team { TeamName = "Malta", FifaAlphaCode = "MLT", TeamCode = "MLT", TypeName= "National" },
                new Team { TeamName = "Mauritania", FifaAlphaCode = "MTN", TeamCode = "MTN", TypeName= "National" },
                new Team { TeamName = "Mauritius", FifaAlphaCode = "MRI", TeamCode = "MRI", TypeName= "National" },
                new Team { TeamName = "Mexico", FifaAlphaCode = "MEX", TeamCode = "MEX", TypeName= "National" },
                new Team { TeamName = "Moldova", FifaAlphaCode = "MDA", TeamCode = "MDA", TypeName= "National" },
                new Team { TeamName = "Mongolia", FifaAlphaCode = "MNG", TeamCode = "MNG", TypeName= "National" },
                new Team { TeamName = "Montenegro", FifaAlphaCode = "MNE", TeamCode = "MNE", TypeName= "National" },
                new Team { TeamName = "Montserrat", FifaAlphaCode = "MSR", TeamCode = "MSR", TypeName= "National" },
                new Team { TeamName = "Morocco", FifaAlphaCode = "MAR", TeamCode = "MAR", TypeName= "National" },
                new Team { TeamName = "Mozambique", FifaAlphaCode = "MOZ", TeamCode = "MOZ", TypeName= "National" },
                new Team { TeamName = "Myanmar", FifaAlphaCode = "MYA", TeamCode = "MYA", TypeName= "National" },
                new Team { TeamName = "Namibia", FifaAlphaCode = "NAM", TeamCode = "NAM", TypeName= "National" },
                new Team { TeamName = "Nepal", FifaAlphaCode = "NEP", TeamCode = "NEP", TypeName= "National" },
                new Team { TeamName = "Netherlands", FifaAlphaCode = "NED", TeamCode = "NED", TypeName= "National" },
                new Team { TeamName = "New Caledonia", FifaAlphaCode = "NCL", TeamCode = "NCL", TypeName= "National" },
                new Team { TeamName = "New Zealand", FifaAlphaCode = "NZL", TeamCode = "NZL", TypeName= "National" },
                new Team { TeamName = "Nicaragua", FifaAlphaCode = "NCA", TeamCode = "NCA", TypeName= "National" },
                new Team { TeamName = "Niger", FifaAlphaCode = "NIG", TeamCode = "NIG", TypeName= "National" },
                new Team { TeamName = "Nigeria", FifaAlphaCode = "NGA", TeamCode = "NGA", TypeName= "National" },
                new Team { TeamName = "North Korea", FifaAlphaCode = "PRK", TeamCode = "PRK", TypeName= "National" },
                new Team { TeamName = "North Macedonia", FifaAlphaCode = "MKD", TeamCode = "MKD", TypeName= "National" },
                new Team { TeamName = "Northern Ireland", FifaAlphaCode = "NIR", TeamCode = "NIR", TypeName= "National" },
                new Team { TeamName = "Norway", FifaAlphaCode = "NOR", TeamCode = "NOR", TypeName= "National" },
                new Team { TeamName = "Oman", FifaAlphaCode = "OMA", TeamCode = "OMA", TypeName= "National" },
                new Team { TeamName = "Pakistan", FifaAlphaCode = "PAK", TeamCode = "PAK", TypeName= "National" },
                new Team { TeamName = "Palestine", FifaAlphaCode = "PLE", TeamCode = "PLE", TypeName= "National" },
                new Team { TeamName = "Panama", FifaAlphaCode = "PAN", TeamCode = "PAN", TypeName= "National" },
                new Team { TeamName = "Papua New Guinea", FifaAlphaCode = "PNG", TeamCode = "PNG", TypeName= "National" },
                new Team { TeamName = "Paraguay", FifaAlphaCode = "PAR", TeamCode = "PAR", TypeName= "National" },
                new Team { TeamName = "Peru", FifaAlphaCode = "PER", TeamCode = "PER", TypeName= "National" },
                new Team { TeamName = "Philippines", FifaAlphaCode = "PHI", TeamCode = "PHI", TypeName= "National" },
                new Team { TeamName = "Poland", FifaAlphaCode = "POL", TeamCode = "POL", TypeName= "National" },
                new Team { TeamName = "Portugal", FifaAlphaCode = "POR", TeamCode = "POR", TypeName= "National" },
                new Team { TeamName = "Puerto Rico", FifaAlphaCode = "PUR", TeamCode = "PUR", TypeName= "National" },
                new Team { TeamName = "Qatar", FifaAlphaCode = "QAT", TeamCode = "QAT", TypeName= "National" },
                new Team { TeamName = "Republic of Ireland", FifaAlphaCode = "IRL", TeamCode = "IRL", TypeName= "National" },
                new Team { TeamName = "Romania", FifaAlphaCode = "ROU", TeamCode = "ROU", TypeName= "National" },
                new Team { TeamName = "Russia", FifaAlphaCode = "RUS", TeamCode = "RUS", TypeName= "National" },
                new Team { TeamName = "Rwanda", FifaAlphaCode = "RWA", TeamCode = "RWA", TypeName= "National" },
                new Team { TeamName = "Saint Kitts and Nevis", FifaAlphaCode = "SKN", TeamCode = "SKN", TypeName= "National" },
                new Team { TeamName = "Saint Lucia", FifaAlphaCode = "LCA", TeamCode = "LCA", TypeName= "National" },
                new Team { TeamName = "Saint Vincent and the Grenadines", FifaAlphaCode = "VIN", TeamCode = "VIN", TypeName= "National" },
                new Team { TeamName = "Samoa", FifaAlphaCode = "SAM", TeamCode = "SAM", TypeName= "National" },
                new Team { TeamName = "San Marino", FifaAlphaCode = "SMR", TeamCode = "SMR", TypeName= "National" },
                new Team { TeamName = "São Tomé and Príncipe", FifaAlphaCode = "STP", TeamCode = "STP", TypeName= "National" },
                new Team { TeamName = "Saudi Arabia", FifaAlphaCode = "KSA", TeamCode = "KSA", TypeName= "National" },
                new Team { TeamName = "Scotland", FifaAlphaCode = "SCO", TeamCode = "SCO", TypeName= "National" },
                new Team { TeamName = "Senegal", FifaAlphaCode = "SEN", TeamCode = "SEN", TypeName= "National" },
                new Team { TeamName = "Serbia", FifaAlphaCode = "SRB", TeamCode = "SRB", TypeName= "National" },
                new Team { TeamName = "Seychelles", FifaAlphaCode = "SEY", TeamCode = "SEY", TypeName= "National" },
                new Team { TeamName = "Sierra Leone", FifaAlphaCode = "SLE", TeamCode = "SLE", TypeName= "National" },
                new Team { TeamName = "Singapore", FifaAlphaCode = "SIN", TeamCode = "SIN", TypeName= "National" },
                new Team { TeamName = "Slovakia", FifaAlphaCode = "SVK", TeamCode = "SVK", TypeName= "National" },
                new Team { TeamName = "Slovenia", FifaAlphaCode = "SVN", TeamCode = "SVN", TypeName= "National" },
                new Team { TeamName = "Solomon Islands", FifaAlphaCode = "SOL", TeamCode = "SOL", TypeName= "National" },
                new Team { TeamName = "Somalia", FifaAlphaCode = "SOM", TeamCode = "SOM", TypeName= "National" },
                new Team { TeamName = "South Africa", FifaAlphaCode = "RSA", TeamCode = "RSA", TypeName= "National" },
                new Team { TeamName = "South Korea", FifaAlphaCode = "KOR", TeamCode = "KOR", TypeName= "National" },
                new Team { TeamName = "South Sudan", FifaAlphaCode = "SSD", TeamCode = "SSD", TypeName= "National" },
                new Team { TeamName = "Spain", FifaAlphaCode = "ESP", TeamCode = "ESP", TypeName= "National" },
                new Team { TeamName = "Sri Lanka", FifaAlphaCode = "SRI", TeamCode = "SRI", TypeName= "National" },
                new Team { TeamName = "Sudan", FifaAlphaCode = "SDN", TeamCode = "SDN", TypeName= "National" },
                new Team { TeamName = "Suriname", FifaAlphaCode = "SUR", TeamCode = "SUR", TypeName= "National" },
                new Team { TeamName = "Sweden", FifaAlphaCode = "SWE", TeamCode = "SWE", TypeName= "National" },
                new Team { TeamName = "Switzerland", FifaAlphaCode = "SUI", TeamCode = "SUI", TypeName= "National" },
                new Team { TeamName = "Syria", FifaAlphaCode = "SYR", TeamCode = "SYR", TypeName= "National" },
                new Team { TeamName = "Tahiti", FifaAlphaCode = "TAH", TeamCode = "TAH", TypeName= "National" },
                new Team { TeamName = "Tajikistan", FifaAlphaCode = "TJK", TeamCode = "TJK", TypeName= "National" },
                new Team { TeamName = "Tanzania", FifaAlphaCode = "TAN", TeamCode = "TAN", TypeName= "National" },
                new Team { TeamName = "Thailand", FifaAlphaCode = "THA", TeamCode = "THA", TypeName= "National" },
                new Team { TeamName = "Timor-Leste", FifaAlphaCode = "TLS", TeamCode = "TLS", TypeName= "National" },
                new Team { TeamName = "Togo", FifaAlphaCode = "TOG", TeamCode = "TOG", TypeName= "National" },
                new Team { TeamName = "Tonga", FifaAlphaCode = "TGA", TeamCode = "TGA", TypeName= "National" },
                new Team { TeamName = "Trinidad and Tobago", FifaAlphaCode = "TRI", TeamCode = "TRI", TypeName= "National" },
                new Team { TeamName = "Tunisia", FifaAlphaCode = "TUN", TeamCode = "TUN", TypeName= "National" },
                new Team { TeamName = "Turkey", FifaAlphaCode = "TUR", TeamCode = "TUR", TypeName= "National" },
                new Team { TeamName = "Turkmenistan", FifaAlphaCode = "TKM", TeamCode = "TKM", TypeName= "National" },
                new Team { TeamName = "Turks and Caicos Islands", FifaAlphaCode = "TCA", TeamCode = "TCA", TypeName= "National" },
                new Team { TeamName = "Uganda", FifaAlphaCode = "UGA", TeamCode = "UGA", TypeName= "National" },
                new Team { TeamName = "Ukraine", FifaAlphaCode = "UKR", TeamCode = "UKR", TypeName= "National" },
                new Team { TeamName = "United Arab Emirates", FifaAlphaCode = "UAE", TeamCode = "UAE", TypeName= "National" },
                new Team { TeamName = "United States", FifaAlphaCode = "USA", TeamCode = "USA", TypeName= "National" },
                new Team { TeamName = "Uruguay", FifaAlphaCode = "URU", TeamCode = "URU", TypeName= "National" },
                new Team { TeamName = "U.S. Virgin Islands", FifaAlphaCode = "VIR", TeamCode = "VIR", TypeName= "National" },
                new Team { TeamName = "Uzbekistan", FifaAlphaCode = "UZB", TeamCode = "UZB", TypeName= "National" },
                new Team { TeamName = "Vanuatu", FifaAlphaCode = "VAN", TeamCode = "VAN", TypeName= "National" },
                new Team { TeamName = "Venezuela", FifaAlphaCode = "VEN", TeamCode = "VEN", TypeName= "National" },
                new Team { TeamName = "Vietnam", FifaAlphaCode = "VIE", TeamCode = "VIE", TypeName= "National" },
                new Team { TeamName = "Wales", FifaAlphaCode = "WAL", TeamCode = "WAL", TypeName= "National" },
                new Team { TeamName = "Yemen", FifaAlphaCode = "YEM", TeamCode = "YEM", TypeName= "National" },
                new Team { TeamName = "Zambia", FifaAlphaCode = "ZAM", TeamCode = "ZAM", TypeName= "National" },
                new Team { TeamName = "Zimbabwe", FifaAlphaCode = "ZIM", TeamCode = "ZIM", TypeName= "National" },
                new Team { TeamName = "Czechoslovakia", FifaAlphaCode = "TCH", TeamCode = "TCH", TypeName= "National" },
                new Team { TeamName = "East Germany", FifaAlphaCode = "GDR", TeamCode = "GDR", TypeName= "National" },
                new Team { TeamName = "Korea Republic", FifaAlphaCode = "KOR", TeamCode = "KOR", TypeName= "National" },
                new Team { TeamName = "Cote D'Ivoire", FifaAlphaCode = "CIV", TeamCode = "CIV", TypeName= "National" },
                new Team { TeamName = "Serbia and Montenegro", FifaAlphaCode = "SCG", TeamCode = "SCG", TypeName= "National" },
                new Team { TeamName = "Soviet Union", FifaAlphaCode = "URS", TeamCode = "URS", TypeName= "National" },
                new Team { TeamName = "Zaire", FifaAlphaCode = "ZAI", TeamCode = "ZAI", TypeName= "National" },
                new Team { TeamName = "Yugoslavia", FifaAlphaCode = "YUG", TeamCode = "YUG", TypeName= "National" },
                new Team { TeamName = "Dutch East Indies", FifaAlphaCode = "INH", TeamCode = "INH", TypeName= "National" },
                new Team { TeamName = "USA", FifaAlphaCode = "USA", TeamCode = "USA", TypeName= "National" },
                new Team { TeamName = "West Germany", FifaAlphaCode = "FRG", TeamCode = "FRG", TypeName= "National" }
             );
            context.SaveChanges();
            await context.SaveChangesAsync();
        }
    }
}
